server:
  port: 14514
  datamake_limit: 100000
email:
  host:
  port: 465
  email:
  smtp_pwd:
token:
  expire: 864000
  refresh: 432000
  secret: stuoj
database:
  host:
  port:
  name: stuoj_db
  user: stuoj
  password:
  max_open_conns: 10
  max_idle_conns: 5
judge:
  host:
  port:
  token:
yuki-image:
  host:
  port:
  token:
neko-acm:
  host:
  port:
  token:

