version: '3'
services:
    stuoj:
        container_name: stuoj
        image: crpi-jg7reu90mmam5qch.cn-guangzhou.personal.cr.aliyuncs.com/artdragon/stuoj:latest
        restart: no
        volumes:
            - ./config.yaml:/app/config.yaml
        ports:
            - 14514:14514
